dat <- read.table("household_power_consumption.txt", header = TRUE, sep = ';')
dat$Date <- as.Date(dat$Date, format = "%d/%m/%Y")
dat_use <- subset(dat, Date >= "2007-02-01" & Date <= "2007-02-02")
datetime <- strptime(paste(dat_use$Date, dat_use$Time, sep=" "), "%Y-%m-%d %H:%M:%S") 
png(file = "plot2.png")
plot(datetime, as.numeric(as.character(dat_use$Global_active_power)), type="l", xlab="", ylab="Global Active Power (kilowatts)")
dev.off()