dat <- read.table("household_power_consumption.txt", header = TRUE, sep = ';')
dat$Date <- as.Date(dat$Date, format = "%d/%m/%Y")
dat_use <- subset(dat, Date >= "2007-02-01" & Date <= "2007-02-02")
datetime <- strptime(paste(dat_use$Date, dat_use$Time, sep=" "), "%Y-%m-%d %H:%M:%S")  
png(file = "plot3.png")
plot(datetime, as.numeric(as.character(dat_use$Sub_metering_1)), type="l", xlab="", ylab="Energy Submetering")
lines(datetime, as.numeric(as.character(dat_use$Sub_metering_2)), type = "l", col = 'red')
lines(datetime, as.numeric(as.character(dat_use$Sub_metering_3)), type = "l", col = 'blue')
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty=1, lwd=2.5, col=c("black", "red", "blue"))
dev.off()